### ISSUE TITLE
cvt.Int64转换出错

### ISSUE THREAD

**Issue by klarkxy** [shockerli/cvt#7]
```
package main

import (
	"fmt"

	"github.com/shockerli/cvt"
)

func main() {
	fmt.Print("7138826985640367621", "\n")
	fmt.Print(cvt.Int64("7138826985640367621"), "\n")
}

```
输出
```
7138826985640367621
7138826985640368128
```

**Comment by klarkxy** [comment]
![image](https://user-images.githubusercontent.com/6316992/188205594-a86d7cf2-85c6-4da8-ab35-5b151b79fd41.png)

**Comment by klarkxy** [comment]
改成`strconv.ParseInt(vv, 10, 64)`解决问题

**Comment by shockerli** [comment]
感谢您的反馈。

原转换方案为了兼容浮点数字符串也能转换成数字，故采用了ParseFloat作为中间转换，如：`12.0 => 12`。
故丢失了精度。最新提交，已修复此问题。

**Comment by shockerli** [comment]
已于 [v0.2.2](https://github.com/shockerli/cvt/releases/tag/v0.2.2) 修复
